language: java		
jdk: oraclejdk8

services:
  - mongodb
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/066a8197f92d460e8530
    on_success: always
    on_failure: always  
    on_start: false  
